// enum Fases {
//         Primera,
//         Segunda,
//         Tercera
// }

// console.log(Fases.Primera)

// Null...
let nullExample: null = null; // Solo puede tomar valor "null"...
let numberExample: number = null; // Pero el valor "null" podemos asignarlo
                                                                // a cualquier variable...

// Undefined...
let undefinedExample: undefined = undefined; // Solo puede tomar valor "undefined"...
let stringExample: string = undefined; // Pero el valor "undefined" podemos asignarlo
                                                                // a cualquier variable...
