// enum Fases {
//         Primera,
//         Segunda,
//         Tercera
// }
// console.log(Fases.Primera)
// Null...
var nullExample = null; // Solo puede tomar valor "null"...
var numberExample = null; // Pero el valor "null" podemos asignarlo
// a cualquier variable...
// Undefined...
var undefinedExample = undefined; // Solo puede tomar valor "undefined"...
var stringExample = undefined; // Pero el valor "undefined" podemos asignarlo
// a cualquier variable...
var numb;
var isANumber = numb; // Casteo explícito...
